env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8080"
  timeout: 4s # Time to read and write the response
  idle_timeout: 60s # Time of life of the connection
